before:
  hooks:
  - go mod tidy
  - go generate ./...
  - make build-ui

builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/
  binary: inngest
  ldflags:
  - -s -w
  - -X github.com/inngest/inngest/pkg/inngest/version.Version={{.Version}}
  - -X github.com/inngest/inngest/pkg/inngest/version.Hash={{.ShortCommit}}
  goos:
  - linux
  goarch:
  - amd64

dockers:
- id: inngest-amd64
  goos: linux
  goarch: amd64
  skip_push: false
  use: buildx
  dockerfile: 'Dockerfile.goreleaser'
  image_templates:
  - "ECR_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/inngest:latest"
  - "ECR_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/inngest:{{ .Tag }}"
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--platform=linux/amd64"

archives:
- format_overrides:
  - goos: windows
    format: zip
  files:
  - LICENSE.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

# release:
#   github:
#     owner: thoughtlead-io
#     name: inngest
